//
// AnimalBehavior.cs
// Author: Jerry Fu <jerry@glasslabgames.org>
// 2014 - 12 - 9
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class AnimalBehavior : AnimalBehaviorState
{
  override protected void update()
  {

  }
}

