//
// FoodType.cs
// Author: Jerry Fu <jerry@glasslabgames.org>
// 2014 - 12 - 10
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public enum FoodType
{
  NONE = 0,
  RED,
  BLUE,
  GREEN,
  YELLOW,
  TOTAL_TYPES
}